### ISSUE TITLE
i can't to do claim of MO from my btc wallets

### ISSUE THREAD

**Issue by abadon666** [awhooooo/BTC-BTCMobick#1]
hi sir..i have need of your help
i am mobick fans
i have my 5 btc wallets that i have used in the passed
i can  import them in mobick wallet application
i can see the balance
but when i move them out to the other address i have error and I CAN'T MOVE my MO

error when send: the transaction was rejected by network rules...txvin's previos block height <=672.407

i have done 1 another tentactive with electrum mo wallet but the same error :
i can import them , i can see the balance but i can't move to the other address
error is :
The server returned an error when broadcasting the transaction.

Consider trying to connect to a different server, or updating GNC.

Unknown error

please help me...thanks for your support

**Comment by awhooooo** [comment]
Hello. BTCMobick is a bitcoin hard fork project that was initiated in South Korea in late 2022. (The fork took place in 2019 but for some reason, this cryptocurrency started to gain recognition in 2023, 4 years later.) I have talked to the founders and according to them, they didn't want to go down the path of Bitcoin Cash, so UTXOs under block height 672408 is rejected by BTCMobick consensus rule. The reason behind this is, according to BTCMobick founders, goes like this.

"Lost coins only make everyone else's coins worth slightly more. Think of it as a donation to everyone." This is a statement from Satoshi Nakamoto regarding the "natural deflation" of bitcoin. However, it seems that this statement is far from being true. At the time of this writing, around 19,500,000 BTC has been mined and it is estimated that up to one third of them (about 6,000,000) are considered as lost. Yet, verifying this estimation proves to be an insurmountable challenge. Distinguishing between genuinely lost coins and those that have merely stayed dormant for over a decade remains an impossible task. What we have observed is that Bitcoin's price often experiences turbulence when transactions are made from addresses, especially those with significant balances (the so-called bitcoin whales), previously thought to be lost. The more bitcoin ecosystem grows, the more the unpredictability and noises created during the early days of Bitcoin are being amplified. BTCMobick aims to eliminate these uncertainties to some extent.

Since BTCMobick is a hard-forked blockchain from Bitcoin, transactions made on BTCMobick network imply that the same address is also alive in Bitcoin (since the address and the key structure is identical). The key is to remain inconspicuous to the early-adopters of Bitcoin (2009~2011) and when BTCMobick ecosystem grows and price surges, the BTCMobick founders will temporarily remove the block-height-denial consensus rule. (I have heard that this will take place in 2027). The block range will be open until a certain period of time (say 6 months) and then the block-height-denial consensus rule will be applied again. This is possible because BTCMobick is still maintained private and aims to go public in Jan 3rd 2029 (20th anniversary of Bitcoin). BTCMobick is still in its infancy and opening source code and nodes immaturely is the last thing the founders want to do, as they learned from the mistakes of Bitcoin Cash. 

I have described some basic idea of this new bitcoin-fork project and long story short, you can't claim your balances yet. If you have more questions, feel free to ask!
